name: 'Issues'

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created, edited]

jobs:
  notify:
    name: 'Notify'
    runs-on: ubuntu-latest
    steps:
    - name: 'Debug'
      run: DATA=$(cat "$GITHUB_EVENT_PATH") && echo $DATA
