name: 'Issues'

on:
  issues:
    types: [opened, closed]
  issue_comment:
    types: [created]

jobs:
  notify:
    name: 'Notify'
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout master'
      uses: actions/checkout@v1
    - name: 'Install dependency'
      run: npm install node-fetch
    - name: 'Notify issue'
      run: node ./browser/scripts/notifyIssue.js payloadPath="$GITHUB_EVENT_PATH" steamgiftsToken="${{ secrets.STEAMGIFTS_PHPSESSID }}"
