name: 'Issues'

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  notify:
    name: 'Notify'
    runs-on: ubuntu-latest
    steps:
    - name: 'Debug'
      run: echo github
    - name: 'Checkout dev'
      uses: actions/checkout@v1
    - name: 'Install dependencies'
      run: cd ./browser && npm ci
    - name: 'Notify issue'
      run: cd ./browser && npm run notify-issue payloadPath=$GITHUB_EVENT_PATH phpSessId=${{ secrets.STEAMGIFTS_PHPSESSID }} token=${{ secrets.GITHUB_ACCESS_TOKEN }}
